Documentation - First pass
timoschwarzer/hollow-knight-mod-installer pull request #2
Opened 2017-09-24 21:25 UTC by jozborn

Added descriptions to classes, key variables, and non-overridden methods;

replaced deprecated FileUtils methods by adding CharSet parameter

2017-09-24 22:24 UTC, timoschwarzer requested changes

2017-09-24 22:24 UTC, timoschwarzer commented on src/com/timoschwarzer/hkmodinstaller/data/ModBundle.java
> +        JSONObject manifestObject = new JSONObject(IOUtils.toString(zipFile.getInputStream(manifest), Charset.defaultCharset()));
I don't think using the default OS charset here is a good idea. Imagine one has created a modbundle on a UNIX machine (UTF-8 charset) and opens it on a Windows machine (Windows 1252).
Could you replace `Charset.defaultCharset()` with `StandardCharsets.UTF_8`, please? :smile:

2017-09-24 22:24 UTC, timoschwarzer commented on src/com/timoschwarzer/hkmodinstaller/data/ModDatabase.java
> +            configObject = new JSONObject(FileUtils.readFileToString(configFile, Charset.defaultCharset()));
...same here ;-)

2017-09-24 22:24 UTC, timoschwarzer commented on src/com/timoschwarzer/hkmodinstaller/data/ModDatabase.java
> +        FileUtils.writeStringToFile(new File(this.dataDirectory + "/config.json"), configObject.toString(), Charset.defaultCharset());
... aaaaand here :grin:

2017-09-24 22:26 UTC, timoschwarzer commented
Hi there!

Thank you a lot for doing the things I'm too lazy to do! :sweat_smile: 
Please see my comments and apply the suggestions or leave a comment on them.

2017-09-25 00:08 UTC, jozborn commented
Sure thing! The reason I did used the default charset is because the old write method simply redirected to writeStringToFile with the default charset as an argument. But UTF-8 is definitely better. I'll fix that right up

2017-09-25 01:39 UTC, jozborn commented
All done! I also pulled a couple unused imports just cause.

2017-09-25 04:46 UTC, timoschwarzer commented
Thank you! :)

2017-09-25 04:46 UTC, merged